.github/workflows/main.yml
src/README.md
src/next-app/.eslintrc.json
src/next-app/package.json
src/next-app/pages/index.tsx

Setup CI/CD

---

src/django-app/django-project/shops/serializers.py

Quick fix. I also swapped the address field to use primary key, since we can't guarantee that street is unique.

Django: Fix shop creation endpoint

---

src/django-app/django-project/shops/serializers.py

Swap shop to shop owner in shop serializer

---

src/next-app/components/Button.tsx
src/next-app/constants/api-url.ts
src/next-app/hooks/useForm.ts
src/next-app/pages/create-account.tsx
src/next-app/pages/create-shop.tsx
src/next-app/pages/login.tsx

I made a custom hook for handling form state, for some reason. API is inspired by Formik. Check `create-account.tsx`, `create-shop.tsx`, or `login.tsx` pages for usage.

Better forms

---

src/next-app/components/DateRangePicker.tsx
src/next-app/components/DateRangePickerField.tsx
src/next-app/components/DropdownField.tsx
src/next-app/components/Header.tsx
src/next-app/components/IconButton.tsx
src/next-app/components/Modal.tsx
src/next-app/components/ShopResult.tsx
src/next-app/components/SingleTextField.tsx
src/next-app/components/TextInput.tsx
src/next-app/pages/quote-request.tsx
src/next-app/pages/shop-results.tsx
src/next-app/stories/ShopResults.stories.tsx
src/next-app/styles/components/DateRangePicker.module.css
src/next-app/styles/components/DateRangePickerField.module.css
src/next-app/styles/components/Header.module.css
src/next-app/styles/components/IconButton.module.css
src/next-app/styles/components/Modal.module.css
src/next-app/styles/components/ShopResult.module.css
src/next-app/styles/components/SingleTextField.module.css
src/next-app/styles/pages/Login.module.css
src/next-app/styles/pages/ShopResults.module.css
src/next-app/utils/helper-types.d.ts

Shop results screen

---

src/next-app/components/Header.tsx
src/next-app/stories/Header.stories.tsx
src/next-app/styles/components/Header.module.css
src/next-app/styles/components/IconButton.module.css

- Header component will show 3 dots on right side
- Upon clicking them, a menu with options will be shown
You can check it out in Storybook

Done burger menu with all functionality

---

src/next-app/components/Card.tsx
src/next-app/components/Dropdown.tsx
src/next-app/data/QuoteData.tsx
src/next-app/pages/quote-request-details.tsx
src/next-app/styles/components/Card.module.css
src/next-app/styles/components/Dropdown.module.css
src/next-app/styles/pages/QuoteRequestDetails.module.css

Not able to successfully connect to backend yet. Using dummy data for filter.
This closes #86

86 quote request details page

---

src/django-app/accounts/serializers.py
src/django-app/accounts/views.py
src/django-app/config/urls.py

Backend: Add User Type to JWT create response

---

src/django-app/accounts/serializers.py

Backend: Add auth tokens to registration serializer

---

src/django-app/quotes/models.py
src/django-app/quotes/serializers.py

Quick PR to add a status field to the quote request model.
Closes #125.

Add status field to quote request model

---

src/next-app/components/TextArea.tsx
src/next-app/pages/quote-request.tsx

Add api to quote requests

---

src/django-app/quotes/serializers.py

Fixes an issue with the quote serializer field.

Fix Quote Request Serializer Field

---

src/django-app/config/settings.py
src/next-app/pages/create-account.tsx
src/next-app/pages/work-orders/[id].tsx
src/next-app/utils/api.ts

Employee account creation + Invite Link fixes + Work Order fix

Backend: Employee account creation + Invite Link fixes

---

src/django-app/shops/views.py

This PR fixes AppointmentSlot filters for start and end dates.

Backend: Fix start and end date filteration for AppointmentSlots

---

src/next-app/cypress.config.ts
src/next-app/cypress/e2e/login.cy.ts
src/next-app/cypress/e2e/workorders.cy.ts
src/next-app/cypress/fixtures/example.json
src/next-app/cypress/support/commands.ts
src/next-app/cypress/support/e2e.ts
src/next-app/package.json
src/next-app/pages/work-orders/index.tsx
src/next-app/yarn.lock

Closes #140.
I have added some basic tests for login pages and work-orders.

Testing: Cypress Setup

---

src/django-app/vehicles/policies.py
src/next-app/components/Modal.tsx
src/next-app/pages/services/[id].tsx
src/next-app/pages/services/create-service.tsx
src/next-app/styles/components/Modal.module.css
src/next-app/styles/globals.css

Adds a modal so that shop owners/employees can create new parts on the services pages.

Services: Create new parts on service creation page

---

src/next-app/components/CardComponents.tsx
src/next-app/components/DatePicker.tsx
src/next-app/components/DatePickerField.tsx
src/next-app/components/DateRangePicker.tsx
src/next-app/components/DateRangePickerField.tsx
src/next-app/components/DropdownField.tsx
src/next-app/components/TextInput.tsx
src/next-app/components/TextMultiField.tsx
src/next-app/cypress/e2e/shopRegistration.cy.ts
src/next-app/cypress/support/e2e.ts
src/next-app/package.json
src/next-app/pages/create-account.tsx
src/next-app/yarn.lock

Cypress tests for FT-RT-1 and FT-RT-2

Add registration cypress tests

---

src/django-app/config/settings.py
src/django-app/requirements.txt
src/django-app/shops/policies.py
src/django-app/shops/views.py

Closes #106.
Example request: `http://127.0.0.1:8000/shops/shops/distance/?postal_code=M4B0A3`

Backend: Django Google Maps API for the Shops

---

src/next-app/cypress/e2e/shopRegistration.cy.ts

Added .then to fix shop registration tests.

fixed tests

---

src/next-app/pages/create-shop.tsx

If a shop already exists on a shop owner account then block users from accessing the create shop page. 
Merge this after this pr: https://github.com/HKanwal/kapstone/pull/169 to make sure tests in that PR still pass.

Block create shop page

---

src/django-app/shops/management/commands/generate_appointment_slots.py
src/django-app/shops/policies.py
src/django-app/shops/views.py

Appointment slot creation updates

---

src/django-app/shops/views.py

Fixes the service creation endpoint.

Fix service creation endpoint

---

src/django-app/accounts/views.py
src/django-app/vehicles/policies.py
src/django-app/vehicles/serializers.py
src/next-app/pages/create-appointment.tsx

No form submission yet, as it depends on the previous page being complete.

Add shop owner appointment creation form page

---

src/django-app/accounts/permissions.py
src/django-app/accounts/serializers.py
src/django-app/config/settings.py

This PR fixes the `auth/users/me/` endpoint.

Fix `me` endpoint

---

src/next-app/components/Navbar.tsx
src/next-app/components/ProfileModal.tsx
src/next-app/components/SmallButton.tsx
src/next-app/pages/dashboard.tsx
src/next-app/styles/components/Navbar.module.css
src/next-app/styles/components/ProfileModal.module.css
src/next-app/styles/components/SmallButton.module.css

Mostly changes to NavBar. Fix button sizes, alignments, font sizes, and open/closed state logic of profile and sidebar.

Aesthetic changes

---

src/django-app/vehicles/policies.py

Allows shops to see vehicles with no customer.
Closes #207.

Update vehicle policies

---

src/django-app/misc/policies.py
src/django-app/misc/views.py

This is a potential fix for the notification caching issue.

Fix issue with notification caching

---

src/next-app/components/DropdownField.tsx
src/next-app/components/TextInput.tsx
src/next-app/pages/book-appointment.tsx
src/next-app/pages/dashboard.tsx
src/next-app/pages/find-shop.tsx
src/next-app/pages/quote-request-list.tsx

- Add missing dependencies to useEffect, useMemo calls to address build warnings

Fix most exhaustive deps warnings

---

src/next-app/pages/appointment-form.tsx
src/next-app/pages/book-appointment.tsx
src/next-app/pages/shop-results.tsx
src/next-app/utils/api.ts

Link the customer side appointment creation form to backend

Link appointment form

---

src/next-app/next.config.js
src/next-app/pages/notifications/index.tsx

Disable NextJS caching to fix caching on Notifications

Disable NextJS caching

---

src/next-app/components/BookedAppointment.tsx
src/next-app/pages/appointment-details.tsx
src/next-app/pages/appointment-schedule.tsx
src/next-app/pages/booked-appointments.tsx
src/next-app/pages/dashboard.tsx
src/next-app/pages/employees/[id].tsx
src/next-app/pages/new-quote-requests/[id].tsx
src/next-app/pages/quote-list.tsx
src/next-app/pages/quote-request-details.tsx
src/next-app/pages/quote-request-list.tsx
src/next-app/pages/quote-response.tsx

- routing on appointments
- text overflow on narrow screens
- list sorting
- appointment details page

bug fixes from demo

---

src/django-app/config/settings.py

Revert "Fix images not accessible from Digital Oceans"
